services:
  postgres:
    image: postgres:16
    container_name: tranca_inteligente_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tranca_inteligente
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
