name: Enviar API para o Servidor (preservar .env/bin e reiniciar)

on:
  push:
    branches:
      - US-MQTT
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar rsync e sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      - name: Definir variáveis
        id: vars
        run: |
          echo "PORT=${{ secrets.SERVER_PORT || 22 }}" >> $GITHUB_OUTPUT

      - name: Preparar destino e backups (.env e bin/app)
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_APP_PATH }}
        run: |
          PORT="${{ steps.vars.outputs.PORT }}"
          sshpass -p "$SSH_PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            set -e
            mkdir -p '$REMOTE_PATH'
            if [ -f '$REMOTE_PATH/.env' ]; then cp -f '$REMOTE_PATH/.env' '$REMOTE_PATH/.env.bak'; fi
            if [ -f '$REMOTE_PATH/bin/app' ]; then mkdir -p '$REMOTE_PATH/bin'; cp -f '$REMOTE_PATH/bin/app' '$REMOTE_PATH/bin/app.bak'; fi
          "

      - name: Criar arquivo de exclusões
        run: |
          cat > rsync-excludes.txt <<'EOF'
          .env
          .env.*
          bin/
          uploads/
          storage/
          # adicione outros caminhos que só existem no servidor
          EOF

      - name: Sincronizar pasta api para o servidor (preserva .env/bin)
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_APP_PATH }}
        run: |
          PORT="${{ steps.vars.outputs.PORT }}"
          sshpass -p "$SSH_PASSWORD" rsync -az --delete \
            --exclude-from=rsync-excludes.txt \
            -e "ssh -o StrictHostKeyChecking=no -p $PORT" \
            ./api/ "$SSH_USER@$SSH_HOST:$REMOTE_PATH/"

      - name: Build remoto e restart serviço
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_APP_PATH }}
        run: |
          PORT="${{ steps.vars.outputs.PORT }}"
          sshpass -p "$SSH_PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" '
            set -euo pipefail
            cd "'"$REMOTE_PATH"'"
            mkdir -p bin
            GO_BIN="$(command -v go || true)"
            if [ -z "$GO_BIN" ] && [ -x /snap/bin/go ]; then GO_BIN="/snap/bin/go"; fi
            if [ -z "$GO_BIN" ] && [ -x /usr/local/go/bin/go ]; then GO_BIN="/usr/local/go/bin/go"; fi
            if [ -z "$GO_BIN" ]; then echo "Go não encontrado no PATH do servidor"; exit 1; fi
            "$GO_BIN" version
            "$GO_BIN" mod tidy
            "$GO_BIN" build -o bin/app.new .
            chmod +x bin/app.new
            mv -f bin/app.new bin/app
            # tenta reiniciar como serviço do sistema; se não der, tenta serviço de usuário
            sudo -n systemctl restart api-tranca.service || systemctl --user restart api-tranca.service
          '

      - name: Verificar status (logs recentes)
        if: always()
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          PORT="${{ steps.vars.outputs.PORT }}"
          sshpass -p "$SSH_PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" '
            systemctl is-active api-tranca.service && echo "api-tranca.service ativo" || echo "api-tranca.service inativo ou indisponível"
            journalctl -u api-tranca.service -n 50 --no-pager || true
          '
