name: Deploy Go API to Server with Password

on:
  push:
    branches:
      - US-MQTT # ou a branch que você usa, ex: US-MQTT
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Go binary
        run: |
          cd api
          # Esta é a linha que CRIA o arquivo 'minha-api'
          GOOS=linux GOARCH=amd64 go build -o minha-api

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy binary to server via SCP
        run: |
          # Este comando ENVIA o 'minha-api' para o servidor com um nome temporário
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no ./api/minha-api ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/minha-api-nova

      - name: Execute deploy script on server
        run: |
          # Este comando diz ao servidor para rodar o script assistente
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo /home/${{ secrets.SERVER_USER }}/deploy-api.sh
          EOF