name: Enviar API para o Servidor

on:
  push:
    branches:
      - US-MQTT
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar rsync e sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync sshpass

      # Copia o CONTEÚDO de ./api para SERVER_APP_PATH (note as barras finais)
      - name: Sincronizar pasta api para o servidor
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_APP_PATH }}
          SSH_PORT: ${{ secrets.SERVER_PORT }} # opcional; crie o secret, senão usa 22
        run: |
          PORT="${SSH_PORT:-22}"
          sshpass -p "$SSH_PASSWORD" rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no -p $PORT" \
            ./api/ "$SSH_USER@$SSH_HOST:$REMOTE_PATH/"

      - name: Verificar no servidor (opcional)
        if: always()
        env:
          SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PATH: ${{ secrets.SERVER_APP_PATH }}
          SSH_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          PORT="${SSH_PORT:-22}"
          sshpass -p "$SSH_PASSWORD" ssh -p "$PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "ls -la '$REMOTE_PATH' | head -n 50"
