name: Apenas Enviar a API para o Servidor

on:
  push:
    branches:
      - US-MQTT # ou a branch que você usa
    paths:
      - 'api/**'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Passos para compilar o código (continuam iguais)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Go binary
        run: |
          cd api
          # Esta linha cria o arquivo executável chamado 'minha-api'
          GOOS=linux GOARCH=amd64 go build -o minha-api

      # Passo para instalar a ferramenta de senha
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # --- PASSO DE CÓPIA CORRIGIDO ---
      - name: Copy binary to server directory
        run: |
          # Este comando agora copia o arquivo 'minha-api' PARA DENTRO da pasta
          # que você definiu no secret SERVER_APP_PATH.
          sshpass -p '${{ secrets.SERVER_PASSWORD }}' scp -o StrictHostKeyChecking=no ./api/minha-api ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_APP_PATH }}/